### ISSUE TITLE
unicode in wps status

### ISSUE THREAD

**Issue by davidcaron** [crim-ca/weaver#15]
Using testbed14-twitcher, I got a mysterious result from a wps request. The status was successful, but the results contained an empty list.

I found the bug in `wps_restapi.processes.processes.execute_process()`, when calling `job.save_log(logger=task_logger)`, it raises an exception when the `job.status_message` contains unicode characters.

Also, I think it would be a good idea to refactor the nested try ... except in the monitoring a bit. The error was hard to find because it wasn't logged anywhere except in a debug log that should have been an exception log.

**Comment by fmigneault** [comment]
Not sure if this still happens here? Which `testbed14-twitcher` are you using? It changed quite a bit since the master in `weaver`. I also did some adjustments here and there during jobs logging.

**Comment by davidcaron** [comment]
I'm running testbed14-twitcher 0.4.7. I'll look into it when the time comes to switch to using weaver with the finch deployment. 

The function `weaver.utils.get_job_log_msg` will not work when `message` contains unicode.

**Comment by fmigneault** [comment]
I would recommend changing to weaver first, because a lot of stuff was moved around to remove deprecated or unused stuff. Even new features should be added directly in weaver, because references to obtain the job store and such have changed.

**Comment by davidcaron** [comment]
Should I use the master branch?

**Comment by fmigneault** [comment]
you can use branch `wps1-auto-deploy`
it's pending merge because tests are being implemented, but is ready for everything else
