### ISSUE TITLE
[BUG] invalid `stderr` & `stdout` in case of `workflow` CWL

### ISSUE THREAD

**Issue by fmigneault** [crim-ca/weaver#159]
# Context 

`stderr` & `stdout` extra logging introduced by #132 causes an invalid schema error in the case of `Workflow` CWL definition, as these seem to be valid only in the case of `CommandLineTool`

# Todo 

- had a condition check so that they are not applied for `Workflows`
- had test that validates both added or not in `CommandLineTool` vs `Workflow` cases
- see if all logs (normal + captured by `stderr` & `stdout`) are automatically all aggregated from each step of the `Workflow`, and if not, how to detail correctly the complete `Workflow` log

**Comment by fmigneault** [comment]
@MatProv maybe you can add more details or help working on this?

**Comment by MatProv** [comment]
certainly, I'm working on branch [remove-stdout-stderr-workflow](https://github.com/crim-ca/weaver/tree/remove-stdout-stderr-workflow)

**Comment by fmigneault** [comment]
> certainly, I'm working on branch [remove-stdout-stderr-workflow](https://github.com/crim-ca/weaver/tree/remove-stdout-stderr-workflow)

thanks 👍

**Comment by MatProv** [comment]
Fixed in #166
