### ISSUE TITLE
[Feature] Explicit 'fetch' parameter for some given input

### ISSUE THREAD

**Issue by fmigneault** [crim-ca/weaver#183]
Weaver does a lot of implicit decisions about downloading a file or not in order to try reducing the amount of unnecessary downloads. 

For example, WPS-1 processes monitored by Weaver don't require fetching the file on Weaver side since it will be pulled by the WPS anyway. Same goes for Weaver EMS that dispatches the execution to another ADES.

There are some cases where this behavior could be undesired, or that resolution is ambiguous. 
For example: 
- should an S3 bucket reference be resolved by Weaver EMS to provide it as HTTP to some ADES that cannot access the S3 directly, or should the reference be directly forwarded to the ADES which is the one that has authorization to pull the data?
- What if a process AppPackage needs a file reference, but the app needs to pull it, not Weaver? 

This has to be hacked with a CWL type string for now.

There is a need for some flag that tells explicitly `fetch=True|False` under corresponding WPS-REST inputs to force Weaver to do some download operation or not.

WPS has a parameter `asReference=True|False` for outputs (ie `outputTransmission` in more recent versions) that can indicate if the output result has to be dumped as raw data or provided as file reference, but the same parameter for input doesn't seem to exist (at least to my knowledge).

**Comment by fmigneault** [comment]
@tomLandry @dbyrns 
Tagging you for discussion and considerations in future developments.

**Comment by dbyrns** [comment]
We had this discussion in early days of PAVICS and started using string mimetype for url that should be consumed as is (same as what we do with cwl right now). So no they're is no asReference equivalent for inputs. I see two differents issues here:
1. How an app should express its desire to get an url rather that a file access via CWL (Should be enough to make the decision at the ADES level)
2. How the EMS should handle those inputs. The default strategy for the EMS should be to avoid fetching anything unless we know for sure that the source is private and the EMS has the key to it. In which case, via a known private sources list parameter, we could make the decision to fetch the data and offer a temporary public url for downstream applications.

**Comment by fmigneault** [comment]
I've added some details about the *current* operations applied with file reference: 
https://pavics-weaver.readthedocs.io/en/aws-s3/processes.html#file-reference-types

When in situation of ADES, above link describe best the combinations. 
Case (2) is already working as is, in the sense that anything else than a local file is left as plain file reference for ADES called to handle it.

**Comment by fmigneault** [comment]
Since the creation of this issue, Weaver and OGC API evolved a lot. 
Currently, the "standard" approach to define remote contents is using the following definition: 

```json
{
  "inputs": {
    "input-name": {
      "schema": {
        "type": "string",
        "contentMediaType": "<IANA Media-Type>",
        "contentEncoding": "<optional utf-8|base64|etc.>",
        "contentSchema": "<optional JSON-schema reference>",
       }
    }
  }
}
```

Given that this can be properly distinguished from the "typical" URL string defined as follows:
```json
{
  "inputs": {
    "input-name": {
      "schema": {
        "type": "string",
        "format": "uri | url | uri-reference | url-reference"
       }
    }
  }
}
```

It is possible to define an input that should correspond to a literal URL string passed as-is to the process vs one to be pulled locally and referenced by file-path for execution.
