### ISSUE TITLE
[Feature] Doc landing page improvement

### ISSUE THREAD

**Issue by fmigneault** [crim-ca/weaver#194]
When looking at the landing page of the repo, it can feel quite daunting to understand what is happening in there. 
(https://github.com/crim-ca/weaver)

For external users that are not yet at ease with WPS, ADES, EMS, etc., a quick read of the README can leave one confused. 
(even I wrote it and I can find it quite hard to grasp) 

It would be great to have some kind of nice-yet-simple visual representation of what weaver does. 
I'm thinking about some kind of graphical representation of ADES/EMS architecture that would help new users understand at first glance the purpose of this application. 

So, requesting the help of the video/architecture marketing pros @tomLandry @dbyrns  
If you got some propositions, we can look into it to provide the best end-result.

**Comment by dbyrns** [comment]
I agree we should produce a good looking diagram showing what Weaver does. When our OGC pilot video will be ready it could also be a good thing to add a link here, since it describes pretty well the goal of it and Weaver is named specifically.

**Comment by tomLandry** [comment]
Applications https://www.youtube.com/watch?v=no3REyoxE38
Platforms https://www.youtube.com/watch?v=QkdDFGEfIAY

**Comment by fmigneault** [comment]
Metadata for links

> Applications https://www.youtube.com/watch?v=no3REyoxE38
> Title: Computer Research Institute of Montréal: EO Applications Architecture for Application Developers
Description: The video shares the fundamental ideas behind the architecture, illustrates how application stores for Earth observation data processing can evolve, and illustrates the advantages with applications based on machine learning.
Keywords: Big Data, software architecture, earth observation, satellite data, processing, climate change, machine learning

> Platforms https://www.youtube.com/watch?v=QkdDFGEfIAY
> Description:  The video shares the fundamental ideas behind the architecture,  illustrates how platform managers can benefit from application stores,  and shows the potential for multidisciplinary workflows in thematic  platforms.  Keywords: Big Data, software architecture, earth observation, satellite  data, processing, climate change, machine learning, climate services
