### ISSUE TITLE
[BUG] Failing CWT install of ESGF-compute API

### ISSUE THREAD

**Issue by fmigneault** [crim-ca/weaver#198]
**Describe the bug**

The requirement specified here: 
https://github.com/crim-ca/weaver/blame/d156e01dc9bffa107aa2d3c2fcb3f720d7963c97/setup.py#L53

Constantly results into following error when installing weaver from fresh (or update): 

```
[...]
  File "/home/francis/DEV/miniconda/envs/weaver-py3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/francis/DEV/miniconda/envs/weaver-py3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 785, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cwt' distribution was not found and is required by weaver
Exception ignored in: <module 'threading' from '/home/francis/DEV/miniconda/envs/weaver-py3/lib/python3.7/threading.py'> 
```

The requirement doesn't seem to like very much the different `cwt` vs `esgf-compute-api` package installed.

Furthermore, looking at https://github.com/ESGF/esgf-compute-api/tree/v2.1.0, the `cwt.process` also contain some `print status` operation which is Python-2. 
This is only fixed in v2.2.0, but there are many (potentially breaking) changes also. 
Maybe we should try to request a v2.1.1 with only this statement removed.

In any way, this requirement is extremely breaking weaver install, and must be resolved quickly.

**Comment by MatProv** [comment]
@fmigneault Did it happened during local installation or on brand new instances?
I wonder why during installation of this dependency on Travis we don't have this kind of issue, and how it differs from a fresh install.

**Comment by MatProv** [comment]
Also, I would say that upgrading 2.1.0 to 2.2.0 would not be breaking things up in our case since this dependency has been added really recently in weaver. 

Version 2.1.0 was chosen instead of 2.2.0 only because 2.2.0 wasn't out when the original `esgf-cwt-process` branch has been created, not because 2.2.0 was unsuitable for our needs. 

I think that in our case, going from 2.1.0 to (potentially) 2.1.1, then 2.2.0 would be the same thing as going from 2.1.0 to 2.2.0. Running existing tests to make sure 2.2.0 doesn't break anything in weaver would be the only assertion we can make, since 2.1.0 hadn't been chosen for particular reason, other than "latest available tag".

**Comment by fmigneault** [comment]
> Did it happened during local installation or on brand new instances?
> I wonder why during installation of this dependency on Travis we don't have this kind of issue, and how it differs from a fresh install.

I'm not sure either how come it worked in the first place. I know that pip installer is getting a lot of changes recently to adjust how dependencies are managed. Maybe because of this, an older uncaught issue is now "properly handled" which raises the error?

Regarding 2.2.0, I have done the following and install seems to work: 
https://github.com/crim-ca/weaver/pull/87/commits/2d72672b5a5b89aff81174880e960616a7bb60d7

I'm mostly concerned because functionalities in 2.2.0 might not all work as expected from 2.1.0.
Look at the diff, it is not really a minor change: https://github.com/ESGF/esgf-compute-api/compare/v2.1.0..v2.2.0

**Comment by MatProv** [comment]
Maybe assuming that 2.2.0 works as we assumed that 2.1.0 worked back then would be a possibility. I mean, as far as our tests don't break, other than really understanding all behaviours present in 2.1.0, then checking the 2.1.0..2.2.0 diff, we can't really audit this change in a time efficient manner. 

This reminds me of a conversation that we had related to dependency management and version locks. Before locking `cwltool` or `celery` to a specific version, we used the latest version available. This gives us the benefit of having the most updated versions, without extra effort. Then, when issues on both dependency happened, we locked them to avoid misbehaviour. We could do the same for `esgf-compute-api`, update then lock only if we really need to.

And yes, `DistributionNotFound` issue that you are getting seems to be related to pip. I didn't know about the recent pip dependency management changes, but it can of course be a source of divergence.

I would say that `2d72672` is the way to go for now, and if `esgf-compute-api` gives us pain later on, we might consider investigate more on it later on.

**Comment by fmigneault** [comment]
I am more at ease with `cwltool` and `celery` with close-to-latest dependencies as the community is quite large and packages are tested/updated regularly for important fixes and improvements. I'm not as confident regarding `esgf-compute-api`. Note that 2.2.0 is not even the latest, there are some changes noted as `2.3.4` in commits that are not even tagged, and travis tests only started to work around v2.2.2, which is also not tagged. I'm not quite sure in which state this repo actually is, but at least it is not on critical paths "normal" features of weaver, so we can give a shot to 2.2.0.

**Comment by MatProv** [comment]
Closing the issue as 2.2.0 will be used unless bugs related to this version appears.

**Comment by fmigneault** [comment]
reopen, will close when actually merged.
