### ISSUE TITLE
Data store to stage in CWL

### ISSUE THREAD

**Issue by pedringcoding** [crim-ca/weaver#271]
I have weaver context up, EMS and ADES in hybrid mode, and i like use only one catalog (Data store) in CWL runner. 

When preparing input stage in CWL, This data is consume from CWL file to Catalog or it necessary use ADES to deploy catalog?

In this case, how is the connection established?

Thanks,
Best regards

**Comment by fmigneault** [comment]
Hi @pedringcoding 
I would like to help you but I'm not sure I understand your question. 
Is your issue about how to deploy the CWL in Weaver? Or how to execute that CWL with some data input?

**Comment by pedringcoding** [comment]
Hi @fmigneault 
In particular, I want to access a temporal series from a catalog. The WPS would receive an AOI and a time interval. I would like to know if the data stage in is done by the ADES somehow, or, more probably as I understand, if it is responsability of the CWL to receive the parameters and retrieve the data. My question in the later case is how to pass the API URL (which I guess it is configured in the ADES or the EMS) to the CWL.

Thanks!

**Comment by fmigneault** [comment]
It will depend a lot on the contents and what the app defined in the CWL needs to compute. 
I can see 2 approaches: 

1. You define a custom process that does the stage in with desired inputs. For example, a docker-app that expect `AOI` and `TOI` inputs as strings, and runs the appropriate requests to retrieve the results as outputs. Those staged outputs can then be forwarded to a second process that does the processing operation you want to accomplish on this data.

2. If supported by the catalog, use an OpenSearch query directly. 
    There is some special handling of `EOImage` if the input is an URL that refers to an OpenSearch query. 
    In this situation, the operation to be executed on the data can be packaged into a single app since results from the OpenSearch query are directly retrieved for the process.

    Some examples are defined here: 
    - https://github.com/crim-ca/weaver/tree/master/tests/json_examples
    - https://github.com/crim-ca/weaver/tree/master/tests/opensearch_examples 
    - https://github.com/crim-ca/weaver/blob/master/tests/test_opensearch.py

**Comment by pedringcoding** [comment]
I'll take option 2 to investigate objects of type EOImage with a [FedEO catalog](https://eoportal.org/web/eoportal/fedeo-client). I will review how to execute the cwl's with the examples proposed by you.

Thanks you very much @fmigneault
