### ISSUE TITLE
Support Job execution `Prefer: return` header

### ISSUE THREAD

**Issue by fmigneault** [crim-ca/weaver#414]
## Description

- Allow specification of `return=minimal|representation` in `Prefer` header to control how to return results.
  (equivalent of current `response` parameter in request body, see #376)

## Requirements:

- [x] Provide the `Preference-Applied` header in response with `return` if honored.
- [x] Update `/conformance` requirements
- [x] Conformance items
  - [x] https://github.com/opengeospatial/ogcapi-processes/blob/master/core/recommendations/core/REC_job-results-success-async-many-json-prefer-none.adoc
  - [x] https://github.com/opengeospatial/ogcapi-processes/blob/master/core/recommendations/core/REC_job-results-success-async-many-json-prefer-minimal.adoc
  - [x] https://github.com/opengeospatial/ogcapi-processes/blob/master/core/recommendations/core/REC_job-results-success-async-many-json-prefer-representation.adoc
  - [x] https://github.com/opengeospatial/ogcapi-processes/blob/master/core/recommendations/core/REC_process-execute-success-sync-many-json-prefer-minimal.adoc
  - [x] https://github.com/opengeospatial/ogcapi-processes/blob/master/core/recommendations/core/REC_process-execute-success-sync-many-json-prefer-representation.adoc
  - [x] https://github.com/opengeospatial/ogcapi-processes/blob/master/core/recommendations/core/REC_process-execute-success-sync-many-json-prefer-none.adoc

## References

- return preference: https://datatracker.ietf.org/doc/html/rfc7240#section-4.2
- https://github.com/opengeospatial/ogcapi-processes/issues/215
- relates to #247 
- relates to #376 
- relates to [GD-535](https://crim-ca.atlassian.net/browse/GD-535)
- relates to [DAC-531](https://crim-ca.atlassian.net/browse/DAC-531)

**Comment by christophenoel** [comment]
I like this proposal ! 👍  (even if I'd prefer to see the output resources links available in the job resource aka 'status' 😆 )
