### ISSUE TITLE
Support multiple languages for wps 1 providers

### ISSUE THREAD

**Issue by davidcaron** [crim-ca/weaver#73]
I want to implement multiple languages for WPS 1 providers (pywps providers).

I just wanted to mention that from the OWS Spec, it seems that the way for the user to ask for a language is through the `Accept-Language` header. http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#string_i18n

I couldn't find any parameter in the body of the request... @fmigneault Do you think I'm missing something?

**Comment by fmigneault** [comment]
@davidcaron 
I have seen some `httpAccept=<type>` variants sometime in the query parameters.
I'm not sure exactly methods are supported specifically in pywps. 
For WPS1/2, weaver basically only forwards everything to the pywps server running on the side.
