### ISSUE TITLE
A job's 'percentCompleted' is not the same percent as in the status message

### ISSUE THREAD

**Issue by davidcaron** [crim-ca/weaver#90]
During a WPS1 execution, we can see the percentage at 2 places: in the `percentCompleted` field, and in the `message` field. The value in the message field seems to be the good one.

At one point, the percent shown in the message was 90% (right at the end of the processing, so `REMOTE_JOB_PROGRESS_FETCH_OUT` was the right value), and in the `percentCompleted` field, it was 30%.

After a quick look at the code, I think that the `weaver.process.utils.map_progress` function is called twice (in 2 different places) before being outputted in `percentCompleted`, but once for the value in the status message.

So this one is ok:
https://github.com/crim-ca/weaver/blob/339e57b7a03a82e840c6068ce5919b131afef48f/weaver/processes/wps1_process.py#L132

But this one should treat the progress value as the final percentage I believe (or at least in this case):
https://github.com/crim-ca/weaver/blob/339e57b7a03a82e840c6068ce5919b131afef48f/weaver/processes/wps_package.py#L1709

**Comment by fmigneault** [comment]
This is normal. Most WPS processeses actually report 0-100% only which is not really useful.
To help have at least minimal progression tracking, we report the step of the internal job monitor progress with following steps: 
 https://github.com/crim-ca/weaver/blob/309a69413f2869509438eee3b0e219f06674ff5f/weaver/processes/wps3_process.py#L51-L58

The real percentage is then mapped between 10/90% here, depending on what the WPS process reports using following code. If the process is verbose about progress, we get intermediate values, but at the worst we get 10-90%.

https://github.com/crim-ca/weaver/blob/309a69413f2869509438eee3b0e219f06674ff5f/weaver/processes/wps3_process.py#L300-L301

**Comment by davidcaron** [comment]
Here are a couple status requests while a job runs. Notice the `percentCompleted` value stays at 30% while the `message` shows an increasing progress value.

```
{
  "jobID": "a6cb50f2-7b57-4225-91ea-e7d770e7b4fd",
  "status": "running",
  "message": "Job execution monitoring (progress: 7%, status: Subsetting file 1 of 48).",
  "logs": "https://pavics.climatedata.ca/providers/finch/processes/ensemble_grid_point_heat_wave_frequency/jobs/a6cb50f2-7b57-4225-91ea-e7d770e7b4fd/logs",
  "duration": "0:00:06",
  "percentCompleted": 30
}
{
  "jobID": "a6cb50f2-7b57-4225-91ea-e7d770e7b4fd",
  "status": "running",
  "message": "Job execution monitoring (progress: 22%, status: Subsetting file 18 of 48).",
  "logs": "https://pavics.climatedata.ca/providers/finch/processes/ensemble_grid_point_heat_wave_frequency/jobs/a6cb50f2-7b57-4225-91ea-e7d770e7b4fd/logs",
  "duration": "0:00:10",
  "percentCompleted": 30
}
{
  "jobID": "a6cb50f2-7b57-4225-91ea-e7d770e7b4fd",
  "status": "running",
  "message": "Job execution monitoring (progress: 64%, status: Computing indices for file 8 of 24).",
  "logs": "https://pavics.climatedata.ca/providers/finch/processes/ensemble_grid_point_heat_wave_frequency/jobs/a6cb50f2-7b57-4225-91ea-e7d770e7b4fd/logs",
  "duration": "0:00:38",
  "percentCompleted": 30
}
```

**Comment by fmigneault** [comment]
Ok, I think it's related to the following :

https://github.com/crim-ca/weaver/blob/3372fb3fc038447a1584a067c2ce6ed85b91d646/weaver/wps_restapi/processes/processes.py#L184-L189

Progress in enforced to the 30% while status message is updated on each loop.
We would need to set something like: 

`job.progress = map_progress(execution.percentCompleted, 30, 80)`
